### PR TITLE
'code-improvement': added dynamic voxelization functionality to centerpoint

### PR DESCRIPTION
**Pull request by siddharthanpr**
Enable Dynamic voxelization for centerpoint in the same class ('code-improvement')

### CODE REVIEW

**Comment by meremeev** [comment]
No issues with code, but have design question:
we have separate class for dynamic voxelization
```
@DETECTORS.register_module()
class CenterPoint_dynamicVoxel(MVXTwoStageDetector):
```
Does your changes extend original `CenterPoint` class to `CenterPoint_dynamicVoxel` functionality? 

Also where/how `self.pts_voxel_layer.max_num_points == -1` should be set?

**Comment by siddharthanpr** [comment]
> No issues with code, but have design question: we have separate class for dynamic voxelization
> 
> ```
> @DETECTORS.register_module()
> class CenterPoint_dynamicVoxel(MVXTwoStageDetector):
> ```
> 
> Does your changes extend original `CenterPoint` class to `CenterPoint_dynamicVoxel` functionality?
> 
> Also where/how `self.pts_voxel_layer.max_num_points == -1` should be set?

CenterPoint_dynamicVoxel will go away since it copies code from Centerpoint. this is just a cleaner implementation

`self.pts_voxel_layer.max_num_points = -1`  will be set in the config file

**Comment by ramchandraKarandikar** [comment]
Can we rename this PR to reflect 'code-improvement' to avoid confusion with previous PRs which enable dynamic voxelization?

**Comment by siddharthanpr** [comment]
> 'code-improvement'

Sure, good idea

**Review by mprannoy — APPROVED** [review]

**Review by meremeev — APPROVED** [review]

**Pull request merged**
